# Generated by Django 5.2 on 2025-05-29 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_curso_tutor_materiacurso_profesor'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='especialidad',
            name='grado',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='academico.grado'),
        ),
    ]
