# Generated by Django 5.2 on 2025-05-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0005_curso_tutor_materiacurso_profesor'),
        ('personal', '0002_especialidad_grado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='especialidad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='grado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='especialidad', to='academico.grado'),
        ),
        migrations.AlterUniqueTogether(
            name='especialidad',
            unique_together={('grado', 'materia')},
        ),
    ]
