# Generated by Django 5.2 on 2025-06-06 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_remove_unidadeducativa_admin_fk'),
        ('personal', '0004_profesor_unidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaHoraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horas', models.PositiveSmallIntegerField()),
                ('periodo', models.CharField(blank=True, max_length=20, null=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_horarias', to='personal.especialidad')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_horarias', to='personal.profesor')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cargas_horarias', to='institucion.unidadeducativa')),
            ],
            options={
                'verbose_name': 'Carga Horaria',
                'verbose_name_plural': 'Cargas Horarias',
                'db_table': 'carga_horaria',
                'unique_together': {('profesor', 'especialidad', 'unidad', 'periodo')},
            },
        ),
    ]
