# Generated by Django 5.2 on 2025-06-08 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
        ('personal', '0005_cargahoraria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargahoraria',
            options={'ordering': ['-periodo', '-horas'], 'verbose_name': 'Carga Horaria', 'verbose_name_plural': 'Cargas Horarias'},
        ),
        migrations.AlterUniqueTogether(
            name='cargahoraria',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cargahoraria',
            name='profesor_especialidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cargas_horarias', to='personal.profesorespecialidad'),
        ),
        migrations.AlterField(
            model_name='cargahoraria',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargas_horarias', to='calendario.periodo'),
        ),
        migrations.AddConstraint(
            model_name='cargahoraria',
            constraint=models.UniqueConstraint(fields=('profesor_especialidad', 'periodo'), name='unique_profesor_especialidad_periodo'),
        ),
        migrations.RemoveField(
            model_name='cargahoraria',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='cargahoraria',
            name='profesor',
        ),
        migrations.RemoveField(
            model_name='cargahoraria',
            name='unidad',
        ),
    ]
