# Generated by Django 5.2 on 2025-05-24 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0002_colegio_super_admin_fk_modulo_colegio_fk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='pisos',
            field=models.PositiveSmallIntegerField(default=1, help_text='Número de pisos del módulo'),
        ),
    ]
