# Generated by Django 5.2 on 2025-06-01 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0003_modulo_pisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidadeducativa',
            name='admin_fk',
        ),
    ]
