# Generated by Django 5.2 on 2025-06-04 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('institucion', '0004_remove_unidadeducativa_admin_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='estudiantes', to='institucion.unidadeducativa'),
        ),
    ]
