# Generated by Django 5.2 on 2025-05-23 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_alter_grado_unique_together_grado_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paralelo',
            name='capacidad_maxima',
        ),
    ]
