# Generated by Django 5.2 on 2025-05-27 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_remove_clase_curso_clase_materia_curso_and_more'),
        ('personal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='tutor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_tutorados', to='personal.profesor'),
        ),
        migrations.AddField(
            model_name='materiacurso',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_impartidas', to='personal.profesor'),
        ),
    ]
