# Generated by Django 5.2 on 2025-05-12 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_bitacora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bitacora',
            options={'ordering': ['-fecha'], 'verbose_name': 'Bitácora de sesión', 'verbose_name_plural': 'Bitácoras de sesión'},
        ),
        migrations.AlterModelOptions(
            name='superadmin',
            options={'verbose_name': 'Super Administrador', 'verbose_name_plural': 'Super Administraadores'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('ver', 'Ver'), ('otro', 'Otro')], default='otro', max_length=10, verbose_name='Acción realizada'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción de la acción'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AddField(
            model_name='bitacora',
            name='tabla_afectada',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tabla afectada'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password_reset_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='hora_entrada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Hora de entrada'),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario relacionado'),
        ),
    ]
