# Generated by Django 5.2 on 2025-06-01 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_multitoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ModeloPermitido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Puesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='accion',
            field=models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('listar', 'Listar'), ('otro', 'Otro')], default='otro', max_length=10, verbose_name='Acción realizada'),
        ),
        migrations.AlterField(
            model_name='admin',
            name='puesto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='usuarios.puesto'),
        ),
        migrations.CreateModel(
            name='PermisoPuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.accion')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.modelopermitido')),
                ('puesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='usuarios.puesto')),
            ],
            options={
                'unique_together': {('puesto', 'modelo', 'accion')},
            },
        ),
    ]
