# Generated by Django 5.2 on 2025-06-01 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institucion', '0004_remove_unidadeducativa_admin_fk'),
        ('usuarios', '0006_accion_modelopermitido_puesto_alter_bitacora_accion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admins', to='institucion.unidadeducativa'),
        ),
    ]
